# Generated by Django 4.2.1 on 2023-05-05 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="group",
        ),
    ]
